version: '3.8'

volumes:
  local_mongo_data:

services:

  mongo:
    image: mongo:6.0.4
    volumes:
      - local_mongo_data:/data/db
    env_file:
      - .env
    ports:
      - "27017:27017"

  redis:
    image: redis:7.0.9
    env_file:
      - .env
    ports:
      - "6379:6379"

  api:
    build: .
    volumes:
      - .:/app/
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --reload --host 0.0.0.0
    depends_on:
      - mongo
      - redis
